# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

spring:
    jmx:
        enabled: false
    rabbitmq:
        dynamic: true
        host: localhost
        port: 5672
        username: guest
        password: guest
        listener:
            simple:
                concurrency: 4
                max-concurrency: 8
    main:
        web-application-type: NONE
