# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

server:
    port: 9999
    shutdown: graceful

spring:
    ldap:
        base-dn: dc=springframework,dc=org
    main:
        allow-bean-definition-overriding: false
        web-application-type: SERVLET
